// Mock data — Sparkway Signals (Forest/Porcelain)
const mockData = {
  user: {
    email: "thomas.lefevre@cabinet-altair.fr",
    credits: 27,
    plan: "Pro",
    joinedAt: "Mars 2026",
    perimeter: {
      sectors: ["SaaS B2B", "Fintech", "AI/Data"],
      functions: ["Account Executive", "Sales Manager / Head of Sales", "VP Sales / CRO"],
      regions: ["Île-de-France", "Lyon/Rhône-Alpes", "Remote France"],
    },
  },

  onboarding: {
    sectors: [
      "SaaS B2B", "Fintech", "Healthtech", "E-commerce",
      "Cybersecurity", "AI/Data", "Industrial Tech", "Hardware/IoT", "Other",
    ],
    functions: [
      "Account Executive", "Sales Manager / Head of Sales", "Account Executive",
      "VP Sales / CRO", "Customer Success", "Sales Engineer", "Sales Operations", "Other",
    ],
    regions: [
      "Île-de-France", "Lyon/Rhône-Alpes", "Bordeaux/Sud-Ouest",
      "Marseille/PACA", "Lille/Nord", "Nantes/Ouest", "Toulouse",
      "Remote France", "International",
    ],
  },

  templates: [
    {
      id: "scaleups",
      title: "Scale-ups en hyper-croissance Sales",
      desc: "Boîtes série B/C qui ont +30% effectif Sales sur 6 mois. Friction de sourcing élevée.",
      count: 47,
    },
    {
      id: "stuck",
      title: "Boîtes qui galèrent à recruter",
      desc: "Annonces ouvertes depuis plus de 45 jours, republiées au moins 2 fois.",
      count: 38,
    },
    {
      id: "fundraising",
      title: "Scale-ups en hyper-croissance Sales",
      desc: "Boîtes qui ont closé une levée et qui staffent leur Go-to-Market.",
      count: 29,
    },
    {
      id: "midmarket",
      title: "Mid-Market en ouverture",
      desc: "PME 50-200 personnes qui structurent leur fonction Sales pour la première fois.",
      count: 22,
    },
  ],

  // Results — first one is the freebie, others are teased
  results: {
    template: "Scale-ups en hyper-croissance Sales",
    perimeter: "SaaS B2B / Île-de-France / AE—Sales Manager",
    total: 47,
    freebie: {
      id: "pennylane",
      name: "Pennylane",
      logo: "PL",
      sector: "SaaS Comptabilité",
      city: "Paris 8e",
      size: "520 personnes",
      score: 91,
      flags: [
        "6 postes Sales ouverts",
        "Annonce AE republiée 4x",
        "Levée Série C il y a 5 mois",
      ],
      reco: "Pennylane structure son Mid-Market — c'est exactement ton créneau.",
    },
    teased: [
      { realName: "Spendesk", masked: "S██████", initials: "S", sector: "Fintech B2B", city: "Paris 9e", score: 89, flag: "█ postes Sales ouverts" },
      { realName: "Aircall", masked: "A█████", initials: "A", sector: "Cloud Telephony", city: "Paris 2e", score: 84, flag: "█ postes Sales ouverts" },
      { realName: "Qonto", masked: "Q████", initials: "Q", sector: "Néobanque B2B", city: "Paris 9e", score: 78, flag: "█ postes Sales ouverts" },
      { realName: "Alma", masked: "A███", initials: "A", sector: "Paiement fractionné", city: "Paris 11e", score: 74, flag: "█ postes Sales ouverts" },
      { realName: "Lydia", masked: "L████", initials: "L", sector: "Fintech B2C/B2B", city: "Paris 17e", score: 71, flag: "█ postes Sales ouverts" },
      { realName: "Joko", masked: "J███", initials: "J", sector: "Fintech rewards", city: "Paris 2e", score: 68, flag: "█ postes Sales ouverts" },
      { realName: "Swile", masked: "S████", initials: "S", sector: "RH / Avantages", city: "Montpellier", score: 64, flag: "█ postes Sales ouverts" },
      { realName: "Agicap", masked: "A█████", initials: "A", sector: "SaaS Trésorerie", city: "Lyon", score: 58, flag: "█ postes Sales ouverts" },
    ],
  },

  // Detailed company files (v2 — dense, actionable)
  companies: {
    pennylane: {
      id: "pennylane",
      name: "Pennylane",
      logo: "PL",
      sector: "SaaS Comptabilité B2B",
      size: "520 personnes",
      city: "Paris 8e",
      website: "pennylane.com",
      score: 91,
      reco: "Pennylane traverse une fenêtre courte de difficulté de sourcing : republication 4x de l'AE Mid-Market sur 60 jours, équipe interne RH de 3 personnes seulement, et arrivée récente d'une VP Sales qui a déjà scalé un cabinet partner chez Aircall. Angle gagnant : proposer un mandat exclusif sur 2 postes Senior AE sous 7 jours, avant que la concurrence cabinet ne se positionne.",
      mandate: {
        low: 92000, high: 156000,
        summary: "3-5 placements identifiés · fees 22-25% sur salaires Sales senior estimés 90-130K€",
        breakdown: [
          { role: "3 postes Senior AE", salary: "110K€", rate: "23%", total: "75 900 €" },
          { role: "1 poste Head of Mid-Market", salary: "130K€", rate: "25%", total: "32 500 €" },
          { role: "1 poste Sales Engineer", salary: "90K€", rate: "22%", total: "19 800 €" },
        ],
      },
      decisionMakers: [
        { name: "Arthur Waller", role: "CEO & Co-founder", initials: "AW", tag: "Co-fondateur depuis 2020", tagTone: "sand",
          angle: "Arthur poste régulièrement sur la transition Mid-Market depuis sa série C. Hook : un retour terrain sur les profils AE qui réussissent vs échouent en transition Solo→Mid-Market chez les concurrents." },
        { name: "Marie Dupont", role: "VP Sales", initials: "MD", tag: "Arrivée il y a 5 mois", tagTone: "sage",
          angle: "Marie vient d'Aircall où elle a scalé l'équipe AE de 8 à 35 en 18 mois. Elle connaît les cabs spé. Approche : LinkedIn direct, parler chiffres et profils précis dès le 1er échange." },
        { name: "Thomas Bernard", role: "Head of Talent Acquisition", initials: "TB", tag: "En poste depuis 2 ans", tagTone: "sand",
          angle: "Thomas a publié les 6 annonces Sales lui-même sur LinkedIn. Il porte la charge sourcing seul. Hook empathique : reconnaître la pression et proposer un soulagement immédiat sur 2-3 postes prioritaires." },
        { name: "Sophie Lambert", role: "Head of Mid-Market Sales", initials: "SL", tag: "Promue il y a 8 mois", tagTone: "sage",
          angle: "Sophie est l'utilisatrice finale des recrutements. Approche : la rencontrer en parallèle de Marie pour valider le profil 'ideal AE' — beaucoup de cabs ne le font jamais et ratent le brief." },
      ],
      scoreBreakdown: [
        { label: "Volume de postes", value: 86, note: "6 postes Sales actifs sur 90 jours" },
        { label: "Persistance", value: 94, note: "AE Mid-Market ouvert depuis 52j" },
        { label: "Re-publication", value: 92, note: "Annonce AE republiée 4 fois" },
        { label: "Croissance Sales", value: 88, note: "+34% effectif Sales sur 6 mois" },
      ],
      timeline: [
        { when: "Il y a 8 mois", text: "Sophie Lambert promue Head of Mid-Market Sales" },
        { when: "Il y a 5 mois", text: "Levée Série C de 40M€ (lead Sequoia)" },
        { when: "Il y a 5 mois", text: "Marie Dupont rejoint en VP Sales (ex-Aircall)" },
        { when: "Il y a 3 mois", text: "Première publication Account Executive Mid-Market" },
        { when: "Il y a 2 mois", text: "Republication x2 de l'AE Mid-Market" },
        { when: "Il y a 1 mois", text: "Ouverture de Senior AE Enterprise + Sales Engineer" },
        { when: "Il y a 14 jours", text: "Republication x4 de l'AE Mid-Market" },
        { when: "Aujourd'hui", text: "6 postes Sales ouverts, 0 hire visible sur LinkedIn", now: true },
      ],
      jobs: [
        { title: "Account Executive — Mid-Market France", date: "Publié il y a 14j", republished: true, type: "AE" },
        { title: "Senior AE — Expert-comptable", date: "Publié il y a 21j", republished: false, type: "AE" },
        { title: "Head of Mid-Market Sales", date: "Publié il y a 28j", republished: true, type: "Lead" },
        { title: "SDR Manager France", date: "Publié il y a 35j", republished: false, type: "Mgr" },
        { title: "Account Executive — SMB", date: "Publié il y a 11j", republished: false, type: "AE" },
        { title: "Sales Engineer — Paris", date: "Publié il y a 44j", republished: true, type: "SE" },
      ],
      signals: {
        effectif: "520 personnes",
        growth: "+34% effectif Sales sur 6 mois",
        salesHeadcount: "≈ 65 personnes",
        lastFunding: "Série C — 40M€ (nov. 2024)",
        leadInvestor: "Sequoia Capital",
        stage: "Série C",
        ceo: "Arthur Waller",
      },
    },

    spendesk: {
      id: "spendesk",
      name: "Spendesk",
      logo: "SP",
      sector: "Fintech B2B — Spend management",
      size: "650 personnes",
      city: "Paris 9e",
      website: "spendesk.com",
      score: 89,
      reco: "Spendesk a réorganisé son go-to-market Enterprise sur Q1 2026 et republie deux fois l'AE Enterprise EMEA. Le nouveau CRO arrive d'Algolia avec un track record de cabinet-friendly hiring. Angle gagnant : proposer un mandat ciblé sur le profil 'AE Enterprise senior multi-pays', le plus dur à sourcer en interne.",
      mandate: {
        low: 78000, high: 138000,
        summary: "3-4 placements identifiés · fees 22-25% sur salaires Sales senior 100-140K€",
        breakdown: [
          { role: "2 postes AE Enterprise EMEA", salary: "125K€", rate: "24%", total: "60 000 €" },
          { role: "1 poste Sales Manager DACH", salary: "140K€", rate: "25%", total: "35 000 €" },
          { role: "1 poste Sales Engineer Senior", salary: "100K€", rate: "22%", total: "22 000 €" },
        ],
      },
      decisionMakers: [
        { name: "Rodolphe Ardant", role: "CEO & Co-founder", initials: "RA", tag: "Co-fondateur depuis 2016", tagTone: "sand",
          angle: "Rodolphe parle ouvertement de sa difficulté à recruter les profils Enterprise. Hook : retour structuré sur 3 candidats AE Enterprise placés chez Pigment ou Aircall ces 6 derniers mois." },
        { name: "Nicolas Martin", role: "CRO", initials: "NM", tag: "Arrivé il y a 3 mois", tagTone: "sage",
          angle: "Nicolas vient d'Algolia où il a travaillé avec 2 cabinets externes spécialisés. Approche : message LinkedIn franc, mentionner un candidat spécifique disponible immédiatement, pas de pitch générique." },
        { name: "Léa Rousseau", role: "VP Talent", initials: "LR", tag: "En poste depuis 18 mois", tagTone: "sand",
          angle: "Léa pilote 4 recruteurs internes débordés sur Tech. Sales est son angle mort. Hook : proposer un audit gratuit du funnel AE Enterprise avant tout commercial — elle dira oui en 48h." },
        { name: "Pierre Caron", role: "Head of Enterprise Sales EMEA", initials: "PC", tag: "Promu il y a 4 mois", tagTone: "sage",
          angle: "Pierre est le manager direct des AE recherchés. Il a publié sur LinkedIn ses critères 'profil idéal'. Approche : reformuler son brief en interview structurée, c'est ton ouverture." },
      ],
      scoreBreakdown: [
        { label: "Volume de postes", value: 88, note: "7 postes Sales actifs sur 90 jours" },
        { label: "Persistance", value: 90, note: "AE Enterprise ouvert depuis 48j" },
        { label: "Re-publication", value: 86, note: "Annonce AE EMEA republiée 2 fois" },
        { label: "Croissance Sales", value: 92, note: "+38% effectif Sales sur 6 mois" },
      ],
      timeline: [
        { when: "Il y a 7 mois", text: "Levée Série C de 100M€ (lead Index Ventures)" },
        { when: "Il y a 4 mois", text: "Pierre Caron promu Head of Enterprise Sales EMEA" },
        { when: "Il y a 3 mois", text: "Nicolas Martin rejoint en CRO (ex-Algolia)" },
        { when: "Il y a 2 mois", text: "Annonce de la stratégie Mid-Market DACH" },
        { when: "Il y a 6 semaines", text: "Ouverture AE Enterprise EMEA + Sales Manager DACH" },
        { when: "Il y a 3 semaines", text: "Republication AE Enterprise EMEA" },
        { when: "Aujourd'hui", text: "7 postes Sales ouverts, 1 seul hire AE visible", now: true },
      ],
      jobs: [
        { title: "Account Executive — Enterprise EMEA", date: "Publié il y a 18j", republished: true, type: "AE" },
        { title: "Sales Manager — DACH", date: "Publié il y a 24j", republished: false, type: "Mgr" },
        { title: "AE Mid-Market France", date: "Publié il y a 12j", republished: false, type: "AE" },
        { title: "Senior Sales Engineer", date: "Publié il y a 31j", republished: true, type: "SE" },
        { title: "Head of Enterprise Sales UK", date: "Publié il y a 41j", republished: false, type: "Lead" },
        { title: "SDR Team Lead — Paris", date: "Publié il y a 9j", republished: false, type: "Mgr" },
        { title: "AE — Italy & Spain", date: "Publié il y a 22j", republished: true, type: "AE" },
      ],
      signals: {
        effectif: "650 personnes",
        growth: "+38% effectif Sales sur 6 mois",
        salesHeadcount: "≈ 140 personnes",
        lastFunding: "Série C — 100M€ (sept. 2025)",
        leadInvestor: "Index Ventures",
        stage: "Série C",
        ceo: "Rodolphe Ardant",
      },
    },

    aircall: {
      id: "aircall",
      name: "Aircall",
      logo: "AC",
      sector: "Cloud Telephony B2B",
      size: "780 personnes",
      city: "Paris 2e",
      website: "aircall.io",
      score: 84,
      reco: "Aircall a connu un turnover Sales important sur Q4 2025 et reconstruit son équipe AE EMEA avec 5 ouvertures simultanées en 6 semaines. La nouvelle SVP Sales arrive de Salesforce et privilégie les cabinets boutiques. Angle gagnant : un mandat d'urgence sur 2 postes AE EMEA avec garantie 90 jours.",
      mandate: {
        low: 64000, high: 112000,
        summary: "3 placements identifiés · fees 20-23% sur salaires AE 95-120K€",
        breakdown: [
          { role: "2 postes AE EMEA", salary: "110K€", rate: "22%", total: "48 400 €" },
          { role: "1 poste AE Mid-Market", salary: "95K€", rate: "21%", total: "19 950 €" },
          { role: "1 poste Sales Manager Benelux", salary: "120K€", rate: "23%", total: "27 600 €" },
        ],
      },
      decisionMakers: [
        { name: "Olivier Pailhès", role: "CEO & Co-founder", initials: "OP", tag: "Co-fondateur depuis 2014", tagTone: "sand",
          angle: "Olivier est sensible aux signaux de stabilité d'équipe après le turnover Q4. Hook : un point de vue sur la rétention AE post-onboarding plutôt qu'un pitch direct." },
        { name: "Caroline Petit", role: "SVP Sales EMEA", initials: "CP", tag: "Arrivée il y a 2 mois", tagTone: "sage",
          angle: "Caroline vient de Salesforce et a déjà bossé avec deux cabs spé pendant son passage. Approche : message LinkedIn court avec 1 candidat précis, garantie 90j explicite." },
        { name: "Mathieu Roche", role: "Director of Talent", initials: "MR", tag: "En poste depuis 3 ans", tagTone: "sand",
          angle: "Mathieu connaît tous les cabs de la place. Le différenciant n'est pas le pitch mais la qualité du shortlist. Approche : envoyer 2 profils ciblés directement, sans pitch." },
        { name: "Julien Garnier", role: "Head of Sales France", initials: "JG", tag: "Promu il y a 6 mois", tagTone: "sage",
          angle: "Julien recrute pour son équipe directement. Il préfère les cabs qui connaissent le marché telco/SaaS. Hook : références concrètes de placements chez Ringover, Diabolocom." },
      ],
      scoreBreakdown: [
        { label: "Volume de postes", value: 82, note: "5 postes Sales actifs sur 90 jours" },
        { label: "Persistance", value: 88, note: "AE EMEA ouvert depuis 38j" },
        { label: "Re-publication", value: 78, note: "Annonce AE republiée 3 fois" },
        { label: "Croissance Sales", value: 76, note: "+18% effectif Sales sur 6 mois (post-turnover)" },
      ],
      timeline: [
        { when: "Il y a 9 mois", text: "Restructuration équipe Sales annoncée en interne" },
        { when: "Il y a 6 mois", text: "Julien Garnier promu Head of Sales France" },
        { when: "Il y a 4 mois", text: "Vague de départs Sales (>10 AE EMEA)" },
        { when: "Il y a 2 mois", text: "Caroline Petit rejoint en SVP Sales EMEA (ex-Salesforce)" },
        { when: "Il y a 6 semaines", text: "Ouverture simultanée de 5 postes AE EMEA" },
        { when: "Il y a 3 semaines", text: "Republication AE EMEA et AE Mid-Market" },
        { when: "Aujourd'hui", text: "5 postes Sales ouverts, équipe à reconstruire", now: true },
      ],
      jobs: [
        { title: "Account Executive — EMEA", date: "Publié il y a 22j", republished: true, type: "AE" },
        { title: "AE — Mid-Market France", date: "Publié il y a 31j", republished: true, type: "AE" },
        { title: "Sales Manager — Benelux", date: "Publié il y a 17j", republished: false, type: "Mgr" },
        { title: "Senior AE — Italy", date: "Publié il y a 28j", republished: false, type: "AE" },
        { title: "SDR Team Lead", date: "Publié il y a 14j", republished: false, type: "Mgr" },
      ],
      signals: {
        effectif: "780 personnes",
        growth: "+18% effectif Sales sur 6 mois",
        salesHeadcount: "≈ 175 personnes",
        lastFunding: "Série D — 120M€ (juin 2021)",
        leadInvestor: "Goldman Sachs Asset Mgmt",
        stage: "Série D",
        ceo: "Olivier Pailhès",
      },
    },
  },

  packs: [
    { id: "discovery", name: "Découverte", credits: 30, price: 29, tag: "Beta", tagTone: "sand", perCredit: 0.97, desc: "Pour tester l'outil sur une vague de prospection." },
    { id: "pro", name: "Pro", credits: 100, price: 79, tag: "Recommandé", tagTone: "sage", perCredit: 0.79, desc: "Le rythme d'un consultant qui débloque 4-5 fiches par semaine." },
    { id: "cabinet", name: "Cabinet", credits: 500, price: 299, tag: "Volume", tagTone: "sand", perCredit: 0.60, desc: "Mutualisé pour une équipe de 3 à 6 consultants." },
  ],

  purchaseHistory: [
    { date: "18 avril 2026", pack: "Pack Pro", amount: "79 €", credits: "+100" },
    { date: "12 mars 2026", pack: "Pack Pro", amount: "79 €", credits: "+100" },
    { date: "04 février 2026", pack: "Pack Découverte", amount: "29 €", credits: "+30" },
  ],

  unlockedHistory: [
    { name: "Pennylane", date: "Hier", score: 91 },
    { name: "Spendesk", date: "Il y a 2 jours", score: 89 },
    { name: "Aircall", date: "Il y a 3 jours", score: 84 },
    { name: "Qonto", date: "Il y a 5 jours", score: 78 },
    { name: "Alma", date: "Il y a 7 jours", score: 74 },
  ],
};

window.mockData = mockData;
